import assert from 'node:assert/strict'; import {test} from 'node:test'; import {DesktopService, sanitizeDesktopErrorMessage} from '../src/desktop-tools.js';
class Fake { calls:{name:string,args:Record<string,unknown>}[]=[]; response:unknown={structuredContent:{window:'ok',password:'secret'}}; async callTool(name:string,args:Record<string,unknown>){this.calls.push({name,args}); return this.response;} async close(){} }
test('gated desktop action fails closed without human confirmation and does not call client',async()=>{const fake=new Fake();const service=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});await assert.rejects(service.execute({action:'type_text',stateId:'s1',text:'secret'}),/CONFIRMATION_REQUIRED: type_text\/press_key require explicit human confirmation in TUI/);assert.equal(fake.calls.length,0);});
test('gated desktop action honors rejection and approval callback',async()=>{const rejected=new Fake();const no=new DesktopService(rejected as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'},async()=>false);await assert.rejects(no.execute({action:'press_key',stateId:'s1',key:'Enter'}),/CONFIRMATION_REQUIRED/);assert.equal(rejected.calls.length,0);
const fake=new Fake();const yes=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'},async(request)=>{assert.equal(request.action,'type_text');return true;});const observed=await yes.execute({action:'observe_window',pid:1,windowId:'w'});await yes.execute({action:'type_text',pid:1,windowId:'w',stateId:observed.stateId,text:'secret'});assert.deepEqual(fake.calls.map(call=>call.name),['get_window_state','get_window_state','type_text']);});
test('desktop execute uses per-call confirmation override over default',async()=>{const fake=new Fake();const service=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'},async()=>false);const observed=await service.execute({action:'observe_window',pid:1,windowId:'w'});let prompt='';await service.execute({action:'type_text',pid:1,windowId:'w',stateId:observed.stateId,text:'payload'},undefined,async(request)=>{prompt=`${request.action}:${request.text}`;return true;});assert.equal(prompt,'type_text:payload');});

test('desktop normalizes secure fields and requires opt-in',async()=>{const fake=new Fake();const service=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});const result=await service.execute({action:'list_windows'});assert.equal(fake.calls[0]?.name,'list_windows');assert.match(JSON.stringify(result),/window/);assert.doesNotMatch(JSON.stringify(result),/password|secret/);});
test('desktop redacts secure sibling regardless of marker order',async()=>{const fake=new Fake();fake.response={structuredContent:{value:'LEAK_ME',is_secure:true}};const service=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});const result=await service.execute({action:'list_windows'});assert.doesNotMatch(JSON.stringify(result),/LEAK_ME/);});
test('desktop extracts standard MCP image content without duplicating base64',async()=>{const fake=new Fake();fake.response={content:[{type:'image',data:'aGVsbG8=',mimeType:'image/png'}]};const service=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});const result=await service.execute({action:'observe_window',pid:1,windowId:'w',includeScreenshot:true});assert.equal((result.content as Array<{type:string}>)[0]?.type,'image');assert.doesNotMatch(JSON.stringify(result.data),/aGVsbG8=/);assert.doesNotMatch(JSON.stringify(result.details),/aGVsbG8=/);});
test('desktop guards huge AX payloads with context-guard marker',async()=>{const fake=new Fake();fake.response={structuredContent:{nodes:'A'.repeat(70000)}};const service=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});const result=await service.execute({action:'list_windows'});const text=(result.content as Array<{text:string}>)[0]?.text??'';assert.match(text,/\[context guard/);assert.ok(text.length<70000);});
test('desktop sanitizes driver error text before surfacing to model',async()=>{class Boom extends Fake{async callTool(){throw new Error('driver blew up Bearer abc123 token=supersecret user:pass@example.com');}} const service=new DesktopService(new Boom() as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});await assert.rejects(service.execute({action:'list_windows'}),/Bearer \*\*\*/);assert.ok(!String(await service.execute({action:'list_windows'}).catch(e=>(e as Error).message)).includes('abc123'));});
test('sanitizeDesktopErrorMessage caps length and redacts credential patterns',()=>{assert.match(sanitizeDesktopErrorMessage('x Bearer abc cookie=zzz'),/Bearer \*\*\*/);assert.equal(sanitizeDesktopErrorMessage('y'.repeat(5000)).length<=2000,true);});
test('desktop rejects oversized selectors and out-of-range coords',async()=>{const service=new DesktopService(new Fake() as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});await assert.rejects(service.execute({action:'list_windows',windowId:'w'.repeat(201)}),/INVALID_REQUEST/);await assert.rejects(service.execute({action:'wait',pid:1,windowId:'w',predicate:{text:'t'.repeat(201)}}),/INVALID_REQUEST/);await assert.rejects(service.execute({action:'click',pid:1,windowId:'w',stateId:'s',x:200000}),/INVALID_REQUEST/);});
test('desktop wait sleep aborts promptly on signal',async()=>{class Slow extends Fake{async callTool(){return {structuredContent:{window:'no-match'}};}} const service=new DesktopService(new Slow() as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});const ctl=new AbortController();const started=Date.now();const pending=service.execute({action:'wait',pid:1,windowId:'w',timeoutMs:30000,predicate:{text:'never-appears-zzz'}},ctl.signal);setTimeout(()=>ctl.abort(),150);await assert.rejects(pending);assert.ok(Date.now()-started<10000,'wait did not abort promptly');});
test('desktop redacts secrets in long strings before length guard',async()=>{const fake=new Fake();const payload='ok '.repeat(4500)+' Bearer sk-supersecret-token-99 token=pw-abc';fake.response={structuredContent:{log:payload}};const service=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});const result=await service.execute({action:'list_windows'});const text=JSON.stringify(result);assert.doesNotMatch(text,/sk-supersecret-token-99/);assert.doesNotMatch(text,/pw-abc/);assert.doesNotMatch(text,/\[context guard/);});
test('sanitizeDesktopErrorMessage masks api keys',()=>{assert.match(sanitizeDesktopErrorMessage('call failed API_KEY=supersecret123'),/API_KEY=\*\*\*/);assert.match(sanitizeDesktopErrorMessage('call failed api_key=supersecret123'),/api_key=\*\*\*/i);assert.doesNotMatch(sanitizeDesktopErrorMessage('call failed API_KEY=supersecret123'),/supersecret123/);});
test('desktop bounds aggregate data/details payloads',async()=>{const fake=new Fake();const big:Record<string,string>={};for(let i=0;i<20;i++) big['k'+i]='v'.repeat(9000);fake.response={structuredContent:big};const service=new DesktopService(fake as never,{PI_SEARCH_DESKTOP_AUTOMATION:'1'});const result=await service.execute({action:'list_windows'});assert.equal(typeof result.data,'string');assert.match(result.data as string,/\[context guard/);assert.ok((result.data as string).length<120000);assert.equal(typeof result.details,'string');assert.match(result.details as string,/\[context guard/);assert.ok((result.details as string).length<120000);});
