import { connect, type Socket } from 'node:net';
import { assertOwner, type BrokerEndpoint } from './broker-endpoint.js';
import { BrokerError, BrokerOutcomeError } from './broker-errors.js';
import { capabilityForMethod, isBrokerError, isBrokerWelcome, type BrokerCapability, type BrokerRequest, type BrokerResponse, type BrokerWelcome, type BrokerQuery, type BrokerQueryResponse } from './broker-protocol.js';
import { readBrokerFrames, sendBrokerMessage } from './broker-transport.js';
import { validateReply, validateRequest, type RuntimeRpcReply, type RuntimeRpcV1Request } from './runtime-rpc-protocol.js';
import { isMutationMethod } from './broker-replay.js';
import type { JobSubmissionReceipt } from './broker-state-store.js';
export const PUBLIC_CLI_BROKER_CLIENT_ID = 'northstar-cli';
export interface BrokerClientOptions { endpoint: BrokerEndpoint; projectId: string; clientId: string; capabilities: RuntimeRpcV1Request['method'][]; }
export class BrokerClient {
  private socket: Socket | undefined; private welcome: BrokerWelcome | undefined; private sequence = 0; private pending = new Map<number, (reply: RuntimeRpcReply | JobSubmissionReceipt | undefined) => void>(); private rejectPending = new Map<number, (error: Error) => void>(); private readonly mutationSequences = new Set<number>(); private handshakeError: BrokerError | undefined;
  constructor(private readonly options: BrokerClientOptions) {}
  async connect(): Promise<void> { await assertOwner(this.options.endpoint.rootDir, true); if (process.platform !== 'win32') await assertOwner(this.options.endpoint.socketPath); this.socket = await new Promise<Socket>((resolve, reject) => { const socket = connect(this.options.endpoint.socketPath); socket.once('connect', () => resolve(socket)); socket.once('error', reject); }); this.handshakeError = undefined;
    readBrokerFrames(this.socket, message => { if (!this.welcome) { if (isBrokerError(message)) { this.handshakeError = new BrokerError(message.code); this.fail(this.handshakeError); this.socket?.destroy(); return; } if (!isBrokerWelcome(message) || message.projectId !== this.options.projectId || message.clientId !== this.options.clientId || message.expiresAt <= Date.now() || !message.token || !message.epoch || !message.sessionId) { this.handshakeError = new BrokerError('unauthorized'); this.fail(this.handshakeError); this.socket?.destroy(); return; } const requested = new Set(this.options.capabilities.map(capabilityForMethod)); if (message.capabilities.some(cap => !requested.has(cap))) { this.handshakeError = new BrokerError('scope_denied'); this.fail(this.handshakeError); this.socket?.destroy(); return; } this.welcome = message; return; } if (isBrokerError(message)) { this.fail(new BrokerError(message.code)); this.socket?.destroy(); return; } if ('kind' in message && message.kind === 'response') { const response = message as BrokerResponse; const done = this.pending.get(response.sequence); if (done && validateReply(response.reply).ok) { this.pending.delete(response.sequence); this.rejectPending.delete(response.sequence); this.mutationSequences.delete(response.sequence); done(response.reply); } } else if ('kind' in message && message.kind === 'queryResponse') { const response = message as BrokerQueryResponse; const done = this.pending.get(response.sequence); if (done) { this.pending.delete(response.sequence); this.rejectPending.delete(response.sequence); done(response.receipt); } } }, error => { this.handshakeError = this.welcome ? undefined : error; this.fail(error); });
    const hello = { version: 2 as const, kind: 'hello' as const, clientId: this.options.clientId, projectId: this.options.projectId, requestedCapabilities: [...new Set(this.options.capabilities.map(capabilityForMethod))] as BrokerCapability[] }; sendBrokerMessage(this.socket, hello); await new Promise<void>((resolve, reject) => { const started = Date.now(); const check = () => this.handshakeError ? reject(this.handshakeError) : this.welcome ? resolve() : Date.now() - started > 5_000 ? reject(new BrokerError('transport_closed')) : setTimeout(check, 1); check(); }); }
  async request(request: RuntimeRpcV1Request): Promise<RuntimeRpcReply> { if (!this.socket || !this.welcome) throw new BrokerError('transport_closed'); const valid = validateRequest(request); if (!valid.ok) throw new BrokerError('invalid_frame'); const capability = capabilityForMethod(valid.value.method); if (!this.welcome.capabilities.includes(capability)) throw new BrokerError('scope_denied'); const sequence = ++this.sequence; const message: BrokerRequest = { version: 2, kind: 'request', token: this.welcome.token, epoch: this.welcome.epoch, sessionId: this.welcome.sessionId, sequence, projectId: this.options.projectId, request: valid.value }; return new Promise((resolve, reject) => { this.pending.set(sequence, value => resolve(value as RuntimeRpcReply)); this.rejectPending.set(sequence, reject); if (isMutationMethod(valid.value.method)) this.mutationSequences.add(sequence); try { sendBrokerMessage(this.socket!, message); } catch (error) { this.pending.delete(sequence); this.rejectPending.delete(sequence); this.mutationSequences.delete(sequence); reject(error instanceof Error ? error : new BrokerError('transport_closed')); } }); }
  async querySubmission(requestId: string): Promise<JobSubmissionReceipt | undefined> { if (!this.socket || !this.welcome) throw new BrokerError('transport_closed'); const sequence = ++this.sequence; const message: BrokerQuery = { version: 2, kind: 'query', token: this.welcome.token, epoch: this.welcome.epoch, sessionId: this.welcome.sessionId, sequence, projectId: this.options.projectId, query: { method: 'submissionReceipt', requestId } }; return new Promise((resolve, reject) => { this.pending.set(sequence, value => resolve(value as JobSubmissionReceipt | undefined)); this.rejectPending.set(sequence, reject); try { sendBrokerMessage(this.socket!, message); } catch (error) { this.pending.delete(sequence); this.rejectPending.delete(sequence); reject(error instanceof Error ? error : new BrokerError('transport_closed')); } }); }
  close(): void { this.socket?.destroy(); this.socket = undefined; this.welcome = undefined; this.fail(new BrokerError('transport_closed')); }
  private fail(error: Error): void { for (const [sequence, reject] of this.rejectPending) reject(this.mutationSequences.has(sequence) ? new BrokerOutcomeError() : error); this.pending.clear(); this.rejectPending.clear(); this.mutationSequences.clear(); }
}
