import type { RuntimeRpcV1Request, RuntimeRpcReply } from './runtime-rpc-protocol.js';
import { RUNTIME_RPC_METHODS, validateReply, validateRequest } from './runtime-rpc-protocol.js';
import { BrokerError, type BrokerErrorCode } from './broker-errors.js';
import { type JobSubmissionReceipt } from './broker-state-store.js';
export const BROKER_PROTOCOL_VERSION = 2;
export const BROKER_MAX_FRAME_BYTES = 256 * 1024;
export const BROKER_TOKEN_TTL_MS = 60_000;
export type BrokerCapability = 'runtime:negotiate' | 'runtime:start' | 'runtime:status' | 'runtime:result' | 'runtime:cancel';
export interface BrokerHello { version: 2; kind: 'hello'; clientId: string; projectId: string; requestedCapabilities: BrokerCapability[]; }
export interface BrokerWelcome { version: 2; kind: 'welcome'; epoch: string; clientId: string; sessionId: string; token: string; expiresAt: number; capabilities: BrokerCapability[]; projectId: string; }
export interface BrokerRequest { version: 2; kind: 'request'; token: string; epoch: string; sessionId: string; sequence: number; projectId: string; request: RuntimeRpcV1Request; }
export interface BrokerQuery { version: 2; kind: 'query'; token: string; epoch: string; sessionId: string; sequence: number; projectId: string; query: { method: 'submissionReceipt'; requestId: string }; }
export interface BrokerResponse { version: 2; kind: 'response'; sequence: number; reply: RuntimeRpcReply; }
export interface BrokerQueryResponse { version: 2; kind: 'queryResponse'; sequence: number; receipt?: JobSubmissionReceipt; }
export interface BrokerErrorMessage { version: 2; kind: 'error'; code: BrokerErrorCode; }
export type BrokerMessage = BrokerHello | BrokerWelcome | BrokerRequest | BrokerQuery | BrokerResponse | BrokerQueryResponse | BrokerErrorMessage;
const CAPS: readonly BrokerCapability[] = ['runtime:negotiate','runtime:start','runtime:status','runtime:result','runtime:cancel'];
const ERROR_CODES: readonly BrokerErrorCode[] = ['invalid_frame','frame_too_large','unsupported_version','unauthorized','expired_token','epoch_mismatch','scope_denied','project_denied','endpoint_unsafe','sequence_replay','duplicate_mutation','transport_closed'];
const record = (v: unknown): v is Record<string, unknown> => Boolean(v) && typeof v === 'object' && !Array.isArray(v);
const exact = (v: Record<string, unknown>, keys: readonly string[]) => Object.keys(v).every(k => keys.includes(k));
export function isBrokerHello(v: unknown): v is BrokerHello { if (!record(v) || !exact(v,['version','kind','clientId','projectId','requestedCapabilities']) || v.version !== 2 || v.kind !== 'hello' || typeof v.clientId !== 'string' || typeof v.projectId !== 'string' || !Array.isArray(v.requestedCapabilities)) return false; return v.requestedCapabilities.every(c => typeof c === 'string' && CAPS.includes(c as BrokerCapability)); }
export function isBrokerRequest(v: unknown): v is BrokerRequest { if (!record(v) || !exact(v,['version','kind','token','epoch','sessionId','sequence','projectId','request']) || v.version !== 2 || v.kind !== 'request' || typeof v.token !== 'string' || typeof v.epoch !== 'string' || typeof v.sessionId !== 'string' || typeof v.projectId !== 'string' || typeof v.sequence !== 'number' || !Number.isSafeInteger(v.sequence)) return false; return validateRequest(v.request).ok; }
export function isBrokerQuery(v: unknown): v is BrokerQuery { if (!record(v) || !exact(v,['version','kind','token','epoch','sessionId','sequence','projectId','query']) || v.version !== 2 || v.kind !== 'query' || typeof v.token !== 'string' || typeof v.epoch !== 'string' || typeof v.sessionId !== 'string' || typeof v.projectId !== 'string' || typeof v.sequence !== 'number' || !Number.isSafeInteger(v.sequence) || !record(v.query) || !exact(v.query,['method','requestId']) || v.query.method !== 'submissionReceipt') return false; return typeof v.query.requestId === 'string' && /^[A-Za-z0-9_-]{1,128}$/.test(v.query.requestId); }
export function isBrokerWelcome(v: unknown): v is BrokerWelcome { return record(v) && exact(v,['version','kind','epoch','clientId','sessionId','token','expiresAt','capabilities','projectId']) && v.version === 2 && v.kind === 'welcome' && typeof v.epoch === 'string' && typeof v.clientId === 'string' && typeof v.sessionId === 'string' && typeof v.token === 'string' && typeof v.expiresAt === 'number' && typeof v.projectId === 'string' && Array.isArray(v.capabilities) && v.capabilities.every(c => typeof c === 'string' && CAPS.includes(c as BrokerCapability)); }
export function isBrokerError(v: unknown): v is BrokerErrorMessage { return record(v) && exact(v, ['version','kind','code']) && v.version === 2 && v.kind === 'error' && typeof v.code === 'string' && ERROR_CODES.includes(v.code as BrokerErrorCode); }
export function encodeBrokerFrame(message: BrokerMessage): Buffer { let body: string; try { body = JSON.stringify(message); } catch { throw new BrokerError('invalid_frame'); } const payload = Buffer.from(body); if (payload.length > BROKER_MAX_FRAME_BYTES) throw new BrokerError('frame_too_large'); const frame = Buffer.allocUnsafe(4 + payload.length); frame.writeUInt32BE(payload.length, 0); payload.copy(frame, 4); return frame; }
export function decodeBrokerFrame(frame: Buffer): BrokerMessage { if (frame.length < 4) throw new BrokerError('invalid_frame'); const size = frame.readUInt32BE(0); if (size > BROKER_MAX_FRAME_BYTES || frame.length !== size + 4) throw new BrokerError(size > BROKER_MAX_FRAME_BYTES ? 'frame_too_large' : 'invalid_frame'); let value: unknown; try { value = JSON.parse(frame.subarray(4).toString('utf8')); } catch { throw new BrokerError('invalid_frame'); } if (isBrokerHello(value) || isBrokerRequest(value) || isBrokerQuery(value) || isBrokerWelcome(value) || isBrokerError(value) || (record(value) && exact(value,['version','kind','sequence','reply']) && value.version === 2 && value.kind === 'response' && typeof value.sequence === 'number' && validateReply(value.reply).ok) || (record(value) && exact(value,['version','kind','sequence','receipt']) && value.version === 2 && value.kind === 'queryResponse' && typeof value.sequence === 'number')) return value as BrokerMessage; throw new BrokerError('invalid_frame'); }
export function capabilityForMethod(method: RuntimeRpcV1Request['method']): BrokerCapability { switch (method) { case 'negotiate': return 'runtime:negotiate'; case 'start': return 'runtime:start'; case 'status': return 'runtime:status'; case 'result': return 'runtime:result'; case 'cancelAndSettle': return 'runtime:cancel'; default: throw new BrokerError('scope_denied'); } }
void RUNTIME_RPC_METHODS;
